nomeInput = input("Digite um nome qualquer: ")
empresaInput = input("Digite um nome de empresa qualquer: ")
quantidadeNumerosInput = int(input("Digite um número inteiro qualquer: "))
mediaValorInput = float(input("Digite um número com casa decimal qualquer: "))
print(nomeInput + " trabalha na empresa " + empresaInput)
print("A empresa, " + empresaInput + " possui ", quantidadeNumerosInput, "funcionario(s).")
print("A média do sálario é de R$" + str(mediaValorInput))
print("------------------------------------------------")